package br.com.procon.models.enums;

/**
 * 
 * @author Marlon F. Garcia
 *
 */
public enum Situacao {

	BALCAO, EM_ANDAMENTO, AUTUADO, GERAL, AGUARDA_AR_FORN, AGUARDA_AR_CONS, AUDIENCIA, CARGA,
	NOTIFICAR_FORNECEDOR, NOTIFICAR_CONSUMIDOR, PRAZO, PRAZO_CONSUMIDOR, PRAZO_FORNECEDOR, CONCLUSO,
	ASSESSORIA, DECISAO, BUSCAS, JURIDICO, DESPACHO, ENCERRADO, RESOLVIDO, NAO_RESOLVIDO,
	INSUBSISTENTE;

}
